# const.py
DOMAIN = "deyecloud"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_APP_ID = "app_id"
CONF_APP_SECRET = "app_secret"
CONF_BASE_URL = "base_url"
CONF_START_MONTH = "start_month"

# Define work mode constants
WORK_MODE_SELLING_FIRST = "SELLING_FIRST"
WORK_MODE_ZERO_EXPORT_TO_LOAD = "ZERO_EXPORT_TO_LOAD"
WORK_MODE_ZERO_EXPORT_TO_CT = "ZERO_EXPORT_TO_CT"
WORK_MODE_GREEN_POWER_MODE = "GREEN_POWER_MODE"
WORK_MODE_FULL_CHARGE_MODE = "FULL_CHARGE_MODE"
WORK_MODE_CUSTOMIZED_MODE = "CUSTOMIZED_MODE"

WORK_MODES = {
    WORK_MODE_SELLING_FIRST: "Selling First",
    WORK_MODE_ZERO_EXPORT_TO_LOAD: "Zero Export to Load",
    WORK_MODE_ZERO_EXPORT_TO_CT: "Zero Export to CT",
    WORK_MODE_GREEN_POWER_MODE: "Green Power Mode",
    WORK_MODE_FULL_CHARGE_MODE: "Full Charge Mode",
    WORK_MODE_CUSTOMIZED_MODE: "Customized Mode",
}
